server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb+srv://pinnamsaihemanth:green@cluster0.z6cji.mongodb.net/orders?retryWrites=true&w=majority
      
  application:
    name: ORDER-SERVICE