server:
  port: 8004

spring:
  data:
    mongodb:
      uri: mongodb+srv://pinnamsaihemanth:green@cluster0.z6cji.mongodb.net/payments?retryWrites=true&w=majority
      
  application:
    name: PAYMENT-SERVICE
