
server:
  port: 8003
  
spring:
  data:
    mongodb:
      uri: mongodb+srv://pinnamsaihemanth:green@cluster0.z6cji.mongodb.net/washers?retryWrites=true&w=majority
      
  application:
    name: WASHER-SERVICE